ALTER SESSION SET CONTAINER = XEPDB1;

ALTER SESSION SET CONTAINER = CDB$ROOT;

SELECT * FROM pessoa;

SELECT DBMS_METADATA.GET_DDL('TABLE', 'PESSOA') FROM dual;

SELECT * FROM ALL_CONSTRAINTS WHERE table_name = 'PESSOA';