ALTER SESSION SET CONTAINER = XEPDB1;

ALTER SESSION SET CONTAINER = CDB$ROOT;

ROLLBACK;

COMMIT;

CREATE USER maestro_lider IDENTIFIED BY OrquestraAgape18;

GRANT CONNECT TO maestro_lider;

ALTER USER maestro_lider QUOTA unlimited ON users;

GRANT SELECT ANY TABLE, UPDATE ANY TABLE, INSERT ANY TABLE, DELETE ANY TABLE TO maestro_lider;

